### ISSUE TITLE
omxplayer missing from latest osmc repo

### ISSUE THREAD

**Issue by PeersonLars** [hissingshark/retrOSMCmk2#5] opened 2020-01-12 11:38 UTC
Hello,
on fresh OSMC 2019-11, the retropie setup script (not your script) fails to build emulationstation because omxplayer is missing from OSMC's current repo but raspbian repo still has a working copy.
I suggest adding the following before launching the retropie installer:
```
# install deprecated omxplayer from raspbian repo without which retropie setup will fail and emulationstation is not built (not optional)

            sudo apt-get install gdebi-core
            mkdir -p /home/osmc/RetroPie/omxplayer_install_package
            wget --no-check-certificate -w 4 -O /home/osmc/RetroPie/omxplayer_install_package/omxplayer_20180905+git061425a-1_armhf.deb https://archive.raspberrypi.org/debian/pool/main/o/omxplayer/omxplayer_20180905+git061425a-1_armhf.deb
            sudo gdebi /home/osmc/RetroPie/omxplayer_install_package/omxplayer_20180905+git061425a-1_armhf.deb

# ask whether to remove the omxplayer install package after install

            echo ""
            echo "omxplayer was installed from the raspbian repo. do you want to remove your backup copy of this install package? (if unsure, type no)"
            rm -ir /home/osmc/RetroPie/omxplayer_install_package
```
I submit this change to you because mcobit hasn't been active in years and I don't want to fork yet (not skilled enough to maintain such a script anyways)

**Comment by hissingshark** [comment] 2020-01-28 20:36
Hi, a few questions:

When did this package stop being available?
Why are you needing to build ES.  I thought binaries were already hosted for RPi via RetroPie?

**Comment by ipochto** [comment] 2020-04-04 09:15
Confirm that omxplayer is missing - had to install it manually from  [raspbian repo](https://archive.raspberrypi.org/debian/pool/main/o/omxplayer/omxplayer_20180905+git061425a-1_armhf.deb).
On the OSMC [fresh](http://download.osmc.tv/installers/diskimages/OSMC_TGT_rbp2_20200402.img.gz) install:
```
osmc@osmc:~$ sudo apt-get install omxplayer                                                                                                                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package omxplayer
```
RetroPie-Setup build EmulationStation from sources and needed omxplayer as dependency for EmulationStation and will break installation because can't resolve dependencies. 

Upd: All of this is correct for mcobit's script. Installation with retrOSMCmk2 is ok - just installed. So, I think the issue is not actual for retrOSMCmk2.

**Comment by hissingshark** [comment] 2020-04-11 20:59
@PeersonLars @ipochto 
So the issue as reported is for installation via RetrOSMC, rather than RetrOSMCmk2?

**Comment by ipochto** [comment] 2020-04-11 21:49
Hi, it seems so.

**Comment by hissingshark** [comment] 2020-04-11 22:42
How odd. Well thanks for checking. I'll close this for now then.

**Closed as completed by hissingshark** 2020-04-11 22:42 UTC
