### ISSUE TITLE
retrOSMCmk2 on OSMC Could not install packages

### ISSUE THREAD

**Issue by NoRealImage** [hissingshark/retrOSMCmk2#23] opened 2022-10-26 05:20 UTC
Hello,
I am trying to install Retropie on OSMC on my Raspberry Pi 4B 8GB ram and I get this issue:

Could not install package (s): libxll-xcb-dev libavcodec-dev libavformat-dev libavdevice-dev.

Could not install package (s): python3-urwid python3-sd12

The Retropie launcher image will show in the OSMC menu but when I click it nothing happens. I am assuming it is because these packages were not installed. I spent a couple of hours trying to google a solution but no luck. Unfortunately, I am unable to show a log file because when I tried to access it nothing was visible but a few white lines and some letters here and there. I don't know if it's because Putty was unable to view it or for some other reason. 

Any help would be appreciated. I am new to all this.

**Comment by yves84** [comment] 2023-01-07 11:07
If u try to install the package per hand:
```
osmc@osmc:~$ sudo apt install libusb-1.0-0-dev libx11-xcb-dev libavcodec-dev libavformat-dev libavdevice-dev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsdl2-dev : Depends: libsdl2-2.0-0 (= 2.0.10+5rpi) but 2.0.14+dfsg2-3+deb11u1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

LibSDL2-dev needs libsdl2-2.0-0. Version 2.0.10 is installed but apt will install 2.0.14 and can not do it... why?

```
osmc@osmc:~$ apt show libsdl2-dev
Package: libsdl2-dev
Source: libsdl2
Version: 2.0.14+dfsg2-3+deb11u1
Installed-Size: 6891
Maintainer: Debian SDL packages maintainers <pkg-sdl-maintainers@lists.alioth.debian.org>
Architecture: armhf
Replaces: libsdl-1.3-dev
Depends: libasound2-dev, libdbus-1-dev, libegl1-mesa-dev, libgl1-mesa-dev, libgles-dev, libglu1-mesa-dev, libibus-1.0-dev, libpulse-dev, libsdl2-2.0-0 (= 2.0.14+dfsg2-3+deb11u1), libsndio-dev, libudev-dev, libwayland-dev, libx11-dev, libxcursor-dev, libxext-dev, libxi-dev, libxinerama-dev, libxkbcommon-dev, libxrandr-dev, libxss-dev, libxt-dev, libxv-dev, libxxf86vm-dev, libc6 (>= 2.7), libgl1, libx11-6
Conflicts: libsdl-1.3-dev
Description-en: Simple DirectMedia Layer development files
 SDL is a library that allows programs portable low level access to a video
 framebuffer, audio output, mouse, and keyboard.
 .
 This package contains the files needed to compile and link programs which
 use SDL.
Description-md5: 9a82f59c5790721baad7ffc5f181d3d6
Multi-Arch: same
Homepage: https://www.libsdl.org/
Tag: devel::library, role::devel-lib
Section: libdevel
Priority: optional
Filename: pool/main/libs/libsdl2/libsdl2-dev_2.0.14+dfsg2-3+deb11u1_armhf.deb
Size: 1384260
MD5sum: fbc324d5d1208a720946411809fa1569
SHA256: b0de6cb91517a848451f4dab5ab2c6515c810f9c1fc46a4ee0f31e4dd9099bf1

Package: libsdl2-dev
Status: hold ok installed                                            # <-------------- HERE
Priority: optional
Section: libdevel
Installed-Size: 4442
Maintainer: Debian SDL packages maintainers <pkg-sdl-maintainers@lists.alioth.debian.org>
Architecture: armhf
Multi-Arch: same
Source: libsdl2
Version: 2.0.10+5rpi
Replaces: libsdl-1.3-dev
Depends: libsdl2-2.0-0 (= 2.0.10+5rpi), libc6-dev, libgl1-mesa-dev, libasound2-dev, libudev-dev, libibus-1.0-dev, libdbus-1-dev, fcitx-libs-dev, libsndio-dev, libx11-dev, libxcursor-dev, libxext-dev, libxi-dev, libxinerama-dev, libxkbcommon-dev, libxrandr-dev, libxss-dev, libxt-dev, libxv-dev, libxxf86vm-dev, libegl1-mesa-dev, libgles2-mesa-dev, libglu1-mesa-dev, libdrm-dev, libgbm-dev
Conflicts: libsdl-1.3-dev
Description: Simple DirectMedia Layer development files
 SDL is a library that allows programs portable low level access to a video
 framebuffer, audio output, mouse, and keyboard.
 .
 This package contains files needed if you wish to use the SDL library in your own programs.
Description-md5: 7085696df1cfaa119cbfcae5fa57d437
Homepage: http://www.libsdl.org/
```

The state of libsdl2-dev v2.0.10 is installed and mark as 'hold'. it will not updated or something (maybe some other packages need exactly this version? idk). but if u try to install only libsdl2-dev:

```
osmc@osmc:~$ sudo apt install libsdl2-dev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpulse-dev libpulse-mainloop-glib0 libsdl2-2.0-0 libwayland-bin libwayland-cursor0 libwayland-dev
Suggested packages:
  xdg-utils libwayland-doc
The following NEW packages will be installed:
  libpulse-dev libpulse-mainloop-glib0 libwayland-bin libwayland-cursor0 libwayland-dev
The following held packages will be changed:
  libsdl2-dev
The following packages will be upgraded:
  libsdl2-2.0-0 libsdl2-dev
2 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2058 kB of archives.
After this operation, 3994 kB of additional disk space will be used.
```

it works and u can install the other packages. i dont know why the one package is holded and i hope it dont break any programs....

UPDATE:
some submodules from RetroPie-Setup take old deb files to install libsdl:
```
osmc@osmc:~/downloads/retrOSMCmk2/submodule/RetroPie-Setup$ find . -iname *.deb
./tmp/archives/bullseye/rpi3/kms/libsdl2-2.0-0_2.0.10+5rpi_armhf.deb
./tmp/archives/bullseye/rpi3/kms/libsdl2-dbg_2.0.10+5rpi_armhf.deb
./tmp/archives/bullseye/rpi3/kms/libsdl2-dev_2.0.10+5rpi_armhf.deb
```

but it is a newer version in apt repos. the mix between old deb packages and newer packages from repo is the problem.

Maybe RetroPie take old deb files if u take "install from binary". not good... its a problem from retropie. not from retrOSMCmk2.

**Comment by AntiSol** [comment] 2023-02-02 13:54
Hi

> i dont know why the one package is holded

This package is compiled from source by the retropie installer, then built into a .deb package and installed with dpkg during the install process. That's why it is held. IIRC the source code was coming from a git submodule that was pointing at a specific commit. The .deb files you found weren't downloaded from a repo but compiled from source on your pi during the install process.

I believe that this is an issue around either the retropie setup script or retrosmc using a submodule pointing to a specific version of SDL (which happens to now be older than the one included in the underlying debian). I haven't yet had time to look any deeper and figure out a) if there's a reason it's locked at that particular version b) if there's anything special about this compiled version of SDL (maybe retropie-specific patches of compile options) c) whether it's safe to simply replace this version with the one from the repos (I'm hoping it is and it looks like this worked for @yves84 ?).

FWIW, I have been able to get the core and a few emulators compiled into a working state with the sdl version 2.0.10+5rpi still installed. This doesn't seem to break kodi as far as I can tell, and retropie and all the emulators Ive managed to install are working great (though obviously it makes installing some things impossible, there's a bunch of stuff that wants libsdl-dev).

I'd be interested to hear from @yves84 as to whether everything works ok after upgrading to libsdl2-2.0-0?

**Comment by yves84** [comment] 2023-02-07 16:08
Hi guys,

now i had time to reproduce the error.

It dont work. if restart the retropie setup script  `core package -> package -> retroarch` the script remove and install the old package again.

```
dh_installdeb: warning: Compatibility levels before 10 are deprecated (level 9 in use)
   dh_gencontrol -O--parallel
   dh_md5sums -O--parallel
   dh_builddeb -O--parallel
dpkg-deb: building package 'libsdl2-2.0-0' in '../libsdl2-2.0-0_2.0.10+5rpi_armhf.deb'.
dpkg-deb: building package 'libsdl2-dev' in '../libsdl2-dev_2.0.10+5rpi_armhf.deb'.
dpkg-deb: building package 'libsdl2-dbg' in '../libsdl2-dbg_2.0.10+5rpi_armhf.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../libsdl2_2.0.10+5rpi_armhf.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build .
dpkg-buildpackage: warning: not signing UNRELEASED build; use --force-sign to override
dpkg-buildpackage: info: binary-only upload (no source included)
/home/osmc/RetroPie-Setup
/home/osmc/RetroPie-Setup/tmp/build/sdl2 /home/osmc/RetroPie-Setup
dpkg: warning: downgrading libsdl2-2.0-0:armhf from 2.0.14+dfsg2-3+deb11u1 to 2.0.10+5rpi
(Reading database ... 50952 files and directories currently installed.)
Preparing to unpack libsdl2-2.0-0_2.0.10+5rpi_armhf.deb ...
Unpacking libsdl2-2.0-0:armhf (2.0.10+5rpi) over (2.0.14+dfsg2-3+deb11u1) ...
dpkg: warning: downgrading libsdl2-dev:armhf from 2.0.14+dfsg2-3+deb11u1 to 2.0.10+5rpi                          # <<<<<<<<<<<<<<< HERE
Preparing to unpack libsdl2-dev_2.0.10+5rpi_armhf.deb ...
Unpacking libsdl2-dev:armhf (2.0.10+5rpi) over (2.0.14+dfsg2-3+deb11u1) ...
Setting up libsdl2-2.0-0:armhf (2.0.10+5rpi) ...
Setting up libsdl2-dev:armhf (2.0.10+5rpi) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
```

https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/sdl2.sh#L125

there is a RP
https://github.com/RetroPie/RetroPie-Setup/pull/3607

if i have more time, i can try the PR.

---
I find that the whole process via the package management make it very unstable. There are other ways to include libs or force programs to use libs (like LD_LIBRARY_PATH or with linker options).

Tip: now i'm using PiNN - a boot manager and i have two os installed (Retropie + libreELEC).

**Comment by dbischof90** [comment] 2023-03-09 17:09
@yves84 The PR has been merged - how would you proceed? I agree with you that this whole setup is a bit unfortunate.

**Comment by TermeHansen** [comment] 2023-03-12 20:56
commented these lines out from setup.sh 
https://github.com/hissingshark/retrOSMCmk2/blob/13c9766cc3e9ca16a0a08335b4bd627a9477fddd/setup.sh#L261-L262

so far it seems to run correct on the new master from RetroPie, and install the upstream sdl2 - fingers crossed!

`Unpacking libsdl2-dev:armhf (2.26.3+1rpi) over (2.0.14+dfsg2-3+deb11u1) ...`

edit:
All is good, and running as before...

**Comment by yves84** [comment] 2023-03-17 09:03
If the owner is still alive, he can close this issues.

**Comment by NoRealImage** [comment] 2023-03-18 03:07
Thanks for your help!

**Closed as completed** 2023-03-18 03:07 UTC
